arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
       - joint1
       - joint2
       - joint3
       - joint4
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
/gazebo_ros_control:
    pid_gains:
      joint1: {p: 1000.0, i: 1.0, d: 1.0}
      joint2: {p: 1000.0, i: 1.0, d: 1.0}
      joint3: {p: 1000.0, i: 1.0, d: 1.0}
      joint4: {p: 1000.0, i: 1.0, d: 1.0}
