# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
  gains:
    joint1: {p: 100.0, i: 0.0, d: 0.1}
    joint2: {p: 100.0, i: 0.0, d: 0.1}
    joint3: {p: 100.0, i: 0.0, d: 0.1}
    joint4: {p: 100.0, i: 0.0, d: 0.1}

# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01

# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint1
    - joint2
    - joint3
    - joint4